name: proplilly
description: "Property monitoring and management application"
publish_to: 'none'

#version: 1.0.0+1
version: 1.0.7+8

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons:
  
  # State Management
  provider:

  # Firebase
  firebase_remote_config:
  firebase_core:
  firebase_analytics:
  firebase_messaging:
  
  # Navigation
  go_router:
  
  # Authentication & Storage
  shared_preferences:
  flutter_secure_storage:
  permission_handler: 
  
  # HTTP & API
  http:
  dio:
  
  # Maps & Location
  geolocator:
  geocoding:
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  
  # File & Image Handling
  image_picker:
  file_picker:
  path_provider:
  
  # Forms & Validation
  flutter_form_builder:
  form_builder_validators:
  
  # UI Components
  flutter_svg:
  cached_network_image:
  intl:

  
  # Notifications
  #flutter_local_notifications:
  
  # Payment (if needed)
  # in_app_purchase: ^3.1.11
  
  # Utilities
  uuid:
  url_launcher:
  package_info_plus: ^9.0.0
  fluttertoast: ^9.0.0
  country_state_city_picker: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/proplilly_logo.jfif"


flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - shorebird.yaml

